### ISSUE TITLE
imageGenerator ?

### ISSUE THREAD

**Issue by mdelcourt** [mdelcourt/Panpan#11]
Yo,
C'est quoi "Backend.imageGenerator" ? Tu fais un import de TOUT dans ta fonction test, mais j'ai pas ce fichier... Il a l'air de marcher une fois que tu commentes la ligne en question...

**Comment by tdelcourt** [comment]
C'est supprimé chez moi mais sans doute que le fichier n'était pas suivi par git. Et j'avais encore le .pyc donc ça plantait pas chez moi.
